CI:
    - any: ['.github/**/*']

Documentation:
    - any:
          [
              '.storybook/**/*',
              '**/*.{stories.tsx,stories.ts,stories.jsx,stories.js}',
          ]

Testing:
    - any: ['**/*.{spec.ts,test.tsx,test.ts,spec.tsx}']

Development:
    - any: ['**/*.{md,config.js,config.ts}', 'scripts/**/*']

Dependency update:
    - any: ['package-lock.json']
