name: 'Pull Request Labeler'
on: [pull_request]

jobs:
    labeler:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: IvanFon/super-labeler-action@v1
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'

            # this solution works for file based labels until we fix the 'super-labeler-action'
            - uses: actions/labeler@2.2.0
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
