name: 'Pull Request Labeler'
on: [pull_request]

jobs:
    labeler:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: IvanFon/super-labeler-action@v1
              with:
                  github-token: '${{ secrets.GITHUB_TOKEN }}'
